chat/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'chat'
urlpatterns = [
    path('chatanggota', chatAnggota, name='chatAnggota'),
    path('chatadmin', chatAdmin, name='chatAdmin'),
]

pengiriman/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'pengiriman'
urlpatterns = [
    path('create', createPengiriman, name='createPengiriman'),
    path('update/<str:id>', updatePengiriman, name='updatePengiriman'),
    path('list/<str:page>', listPengiriman, name='listPengiriman'),
    path('delete/<str:id>', deletePengiriman , name='deletePengiriman')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login
urlpatterns = [
    path('', login),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('user/', include('user.urls')),
    path('barang/', include('barang.urls')),
    path('chat/', include('chat.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
]

pengiriman/models.py
from django.db import models

# Create your models here.
class Pengiriman(models.Model):
    tanggal=models.DateField()
    metode=models.CharField(max_length=100)

# class BarangPesanan(models.Model):
#     BARANG1 = '1'
#     BARANG2 = '2'
#     BARANG3 = '3'
#     BARANG4 = '4'
#     PESANAN_CHOICES = (
#         (BARANG1, 'Barang 1'),
#         (BARANG2, 'Barang 2'),
#         (BARANG3, 'Barang 3'),
#         (BARANG4, 'Barang 4')
#     )

# class Alamat(models.Model):
#     ALAMAT1 = '1'
#     ALAMAT2 = '2'
#     ALAMAT3 = '3'
#     ALAMAT4 = '4'
#     ALAMAT_CHOICES = (
#         (ALAMAT1, 'Alamat 1'),
#         (ALAMAT2, 'Alamat 2'),
#         (ALAMAT3, 'Alamat 3'),
#         (ALAMAT4, 'Alamat 4')
#     )

# class BarangPengiriman(models.Model):
#     BARANG1 = '1'
#     BARANG2 = '2'
#     BARANG3 = '3'
#     BARANG4 = '4'
#     PENGIRIMAN_CHOICES = (
#         (BARANG1, 'Barang 1'),
#         (BARANG2, 'Barang 2'),
#         (BARANG3, 'Barang 3'),
#         (BARANG4, 'Barang 4')
#     )

pengiriman/forms.py
from django import forms
from user.models import Pengiriman
from django.core.exceptions import ValidationError
from django.db import connection

tanggal_attrs = {
    'type': 'date',
    'class': 'form-control form-border-pink',
}

metode_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder':'Metode Pengiriman',
}

multiselect_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
}

review_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder':'Review Barang',
}

def barang_choices(no_ktp):
    with connection.cursor() as c:
        c.execute("select id_barang from barang_pesanan b, pemesanan p where no_ktp_pemesan = %s and p.id_pemesanan = b.id_pemesanan", [no_ktp])
        ids = c.fetchall()
        result = [(i[0], i[0]) for i in ids]
        return result


def alamat_choices(no_ktp):
    with connection.cursor() as c:
        c.execute("select a.nama from alamat a, pengiriman p where a.no_ktp_anggota = %s and a.no_ktp_anggota = p.no_ktp_anggota", [no_ktp])
        alamat = c.fetchall()
        result = [(i[0], i[0]) for i in alamat]
        return result


class PengirimanForm(forms.Form):
    # BARANG1 = '1'
    # BARANG2 = '2'
    # BARANG3 = '3'
    # BARANG4 = '4'
    # PESANAN_CHOICES = (
    #     (BARANG1, 'Barang 1'),
    #     (BARANG2, 'Barang 2'),
    #     (BARANG3, 'Barang 3'),
    #     (BARANG4, 'Barang 4')
    # )

    # ALAMAT1 = '1'
    # ALAMAT2 = '2'
    # ALAMAT3 = '3'
    # ALAMAT4 = '4'
    # ALAMAT_CHOICES = (
    #     (ALAMAT1, 'Alamat 1'),
    #     (ALAMAT2, 'Alamat 2'),
    #     (ALAMAT3, 'Alamat 3'),
    #     (ALAMAT4, 'Alamat 4')
    # )

    def __init__(self,no_ktp, *args, **kwargs):
        super(PengirimanForm, self).__init__(*args, **kwargs)
        self.no_ktp = str(no_ktp)
        self.fields['barang_pesanan'] = forms.MultipleChoiceField(label="Barang Pesanan", widget=forms.SelectMultiple(attrs=multiselect_attrs), choices=barang_choices(self.no_ktp))
        self.fields['alamat'] = forms.MultipleChoiceField(label = "Alamat", widget=forms.SelectMultiple(attrs=multiselect_attrs), choices=alamat_choices(self.no_ktp))
    
    tanggal = forms.DateField(label="Tanggal", widget=forms.DateInput(attrs=tanggal_attrs))
    metode = forms.CharField(label="Metode", max_length= 100, widget=forms.TextInput(attrs=metode_attrs))

    

pengiriman/views.py
from django.shortcuts import render
from .forms import PengirimanForm
from user.models import *
from django.db import connection
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import string
import random
# Create your views here.
def createPengiriman(request):
    if request.method == "POST":
        form = PengirimanForm(request.session['no_ktp'], request.POST )
        if form.is_valid():
            buat_pengiriman(form, request.session['no_ktp'])
            return HttpResponseRedirect('/pengiriman/list/1')
        else:
            print(form.errors)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        forms = PengirimanForm(no_ktp=request.session['no_ktp'])
        # forms = PengirimanForm(role=request.session['role'],no_ktp=request.session['no_ktp'])
        return render(request, 'pengiriman/createPengiriman.html', {'forms':forms})

def updatePengiriman(request,id):
    with connection.cursor() as c:
        c.execute("select * from pengiriman where no_resi=%s", [id])
        pengiriman = c.fetchall()
        print(pengiriman)
        c.execute
    forms = PengirimanForm(no_ktp=request.session['no_ktp'])
    # forms = PengirimanForm(role=request.session['role'],no_ktp=request.session['no_ktp'])
    return render(request, 'pengiriman/updatePengiriman.html', {'forms':forms})

def listPengiriman(request, page):
    no_ktp = request.session['no_ktp']
    role = request.session['role']
    with connection.cursor() as cursor:
        if role == 'admin':
            cursor.execute(
                'SELECT p.no_resi, tanggal, b.id_barang, p.id_pemesanan, (m.harga_sewa+p.ongkos) as total FROM PENGIRIMAN p, BARANG_PESANAN b , PEMESANAN m WHERE p.id_pemesanan = b.id_pemesanan and p.id_pemesanan = m.id_pemesanan'
            )
        else :
            cursor.execute(
                'SELECT p.no_resi, tanggal, b.id_barang, p.id_pemesanan, (m.harga_sewa+p.ongkos) as total FROM PENGIRIMAN p, BARANG_PESANAN b , PEMESANAN m WHERE p.id_pemesanan = b.id_pemesanan AND no_ktp_pemesan = %s and p.id_pemesanan=m.id_pemesanan',[no_ktp]
            )
        list_pengiriman = cursor.fetchall()
    data_pengiriman = [{'id_pengiriman':i[0],
        'tanggal' : i[1],
        'daftar_barang': i[2],
        'id_pemesanan': i[3],
        'harga_total': i[4],
    } for i in list_pengiriman]
    paginator = Paginator(data_pengiriman, 10)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    return render(request, 'pengiriman/listPengiriman.html', {'daftar_pengiriman':data})

def deletePengiriman(request,id):
    with connection.cursor() as c:
        c.execute("DELETE FROM PENGIRIMAN WHERE no_resi = %s", [id])
        return HttpResponseRedirect("/pengiriman/list/1")

def buat_pengiriman(form, ktp):
    alpha_numeric = string.ascii_uppercase + string.digits
    no_resi = ''.join(random.choice(alpha_numeric))
    data_pengiriman = [form.cleaned_data.get('barang_pesanan'),form.cleaned_data.get('alamat'),form.cleaned_data.get('tanggal'),form.cleaned_data.get('metode')]
    print(data_pengiriman)
    id_barang = data_pengiriman[0] 
    with connection.cursor() as c:
        c.execute("select b.id_pemesanan, b.id_barang, ongkos from barang_pesanan b, pemesanan p where no_ktp_pemesan = %s and p.status = 'SEDANG DISIAPKAN' and p.id_pemesanan=b.id_pemesanan", [ktp])
        data=c.fetchall()
        if(not data):
            return HttpResponseRedirect("/pengiriman/list/1")
        print(data)
        ongkos=data[0][2]
        id_pemesanan=data[0][0]
        for i in range(len(data)):
            if data_pengiriman[0][0] == id_barang:
                id_pemesanan = data[i][0]
                ongkos = data[i][2]
            c.execute("INSERT INTO PENGIRIMAN VALUES(%s, %s, %s, %s, %s, %s, %s)", [no_resi, id_pemesanan, data_pengiriman[3], ongkos, data_pengiriman[2], ktp, data_pengiriman[1][0]])

pengiriman/templates/pengiriman/createPengiriman.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="{%static 'css/hira/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
<link href="{%static 'css/hira/multi-select.css'%}" media="screen" rel="stylesheet" type="text/css">
<script type = "text/javascript" src = "{% static 'js/pengiriman/adiva.js' %}" ></script>
{%endblock%}
{%block title%}
Create Shipping
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12 form-border">
            <form action="{%url 'pengiriman:createPengiriman'%}" method="post" class="p-5">
                <h1 class="text-center font-weight-bold">Buat Pengiriman</h1>
                {%csrf_token%}
                <div class="form-group">
                    <h5>Barang Pesanan</h5>
                    {{forms.barang_pesanan}}
                </div>
                <div class="form-group">
                    <h5>Alamat Tujuan</h5>
                    {{forms.alamat}}
                </div>
                <div class="form-group">
                    <h5>Tanggal Pengiriman</h5>
                    {{forms.tanggal}}
                </div>
                <div class="form-group">
                    <h5>Metode</h5>
                    {{forms.metode}}
                </div>
                <!-- <button type="button" class="btn btn-primary btn-lg btn-block btn-pink" data-toggle="modal" data-target="#myModal"> Submit </button> -->
                <div>
                    <!-- <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Submit</button> -->
                    <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink" data-toggle="modal"
                                    data-target="#myModal">Submit</button>
                </div>
                <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title" align="left;">Confirmation</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                        </div>
                        <div class="modal-bodya">
                            <p>Apakah anda yakin dengan pengiriman?</p>
                        </div>
                        <div class="modal-footer">
                            <!-- <button type="button" class="btn btn-success" data-dismiss="modal">Lanjutkan</button> -->
                            <a href="/pengiriman/list/1" class="btn btn-success">Lanjutkan</a>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Batalkan</button>
                        </div>
                    </div>

                </div>
            </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

pengiriman/templates/pengiriman/listPengiriman.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/item/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
List of Shippings
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-9">
            <select id="filter" style="position: relative; left: 100px; top: -5px; width: 240px; height:30px;">
                <option value="volvo">Filter</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
            </select>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id Pengiriman</th>
                        <th scope="col">Daftar Barang - Id Pemesanan</th>
                        <th scope="col">Harga Total</th>
                        <th scope="col">Tanggal Pengiriman</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in daftar_pengiriman %}
                    <tr>
                        <th scope="row">{{i.id_pengiriman}}</th>
                        <td>
                            <ol>{{i.daftar_barang}} - {{i.id_pemesanan}}</ol>
                        </td>
                        <td>{{i.harga_total}}</td>
                        <td>{{i.tanggal}}</td>
                        <td>
                            <a href="/pengiriman/update/{{i.id_pengiriman}}"><button type="button"
                                    class="btn btn-primary">Update</button></a>
                            <div class="anggota-only">
                                <button type="button" class="btn btn-danger" data-toggle="modal"
                                data-target="#m{{i.id_pengiriman}}">Delete</button>
                                <a href="/review/add/"><button type="button" class="btn btn-success">Tulis
                                    Review</button></a>
                            </div>
                        </td>
                    </tr>
                    <!-- Modal -->
                    <div class="modal fade" id="m{{i.id_pengiriman}}" role="dialog">
                            <div class="modal-dialog">
            
                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" align="left;">DELETE NOTIFICATION</h4>
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    </div>
                                    <div class="modal-body">
                                        <p>Apakah anda yakin untuk menghapus pengiriman tersebut?</p>
                                    </div>
                                    <div class="modal-footer">
                                        <!-- <button type="button" class="btn btn-success" data-dismiss="modal">Ya</button> -->
                                        <a href="/pengiriman/delete/{{i.id_pengiriman}}" class="btn btn-success">Ya</a>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
                                    </div>
                                </div>
            
                            </div>
                        </div>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <!-- <div class="row">
        <div class="view">
            <nav aria-label="Page navigation example">
                <ul class="pagination" contenteditable="true">
                    <li class="page-item"><a class="page-link" href="#" style="color : black">Previous</a></li>
                    <li class="page-item"><a class="page-link" href="#" style="color : black">2</a></li>
                    <li class="page-item"><a class="page-link" href="#" style="color : black">3</a></li>
                    <li class="page-item"><a class="page-link" href="#" style="color : black">4</a></li>
                    <li class="page-item"><a class="page-link" href="#" style="color : black">5</a></li>
                    <li class="page-item"><a class="page-link" href="#" style="color : black">Next</a></li>
                </ul>
            </nav>
        </div>
    </div> -->
    {%if daftar_pengiriman.has_other_pages%}
  <div class="row">
    <div class="view">
      <nav aria-label="Page navigation example">
        <ul class="pagination">
          {%if daftar_pengiriman.has_previous %}
          <li class="page-item"><a class="page-link" href="/pengiriman/list/{{pengiriman.previous_page_number}}">Previous</a></li>
          {% endif %}
          {% for i in daftar_pengiriman.paginator.page_range%}
          <li class="page-item"><a class="page-link" href="/pengiriman/list/{{i}}" style="color : black">{{i}}</a></li>
          {% endfor %}
          {% if daftar_pengiriman.has_next %}
          <li class="page-item"><a class="page-link" href="/pengiriman/list/{{pengiriman.next_page_number}}" style="color : black">Next</a></li>
         
          {% endif %}
        </ul>
      </nav>
    </div>
  </div>
  {%endif%}
</div>
{%endblock%}

pengiriman/templates/pengiriman/updatePengiriman.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/item/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Update Shipping
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="text-center">
            <h1 class="font-weight-bold">Update Pengiriman</h1>
        </div>
        <div class="col-12 form-border update-item p-5">
            <form action="/pengiriman/update/" method="post" class="p-5">
                <h1 class="text-center font-weight-bold">Buat Pengiriman</h1>
                {%csrf_token%}
                <div class="form-group">
                    <h5>Barang Pesanan</h5>
                    {{forms.barang_pesanan}}
                </div>
                <div class="form-group">
                    <h5>Alamat Tujuan</h5>
                    {{forms.alamat}}
                </div>
                <div class="form-group">
                    <h5>Tanggal Pengiriman</h5>
                    {{forms.tanggal}}
                </div>
                <div class="form-group">
                    <h5>Metode</h5>
                    {{forms.metode}}
                </div>
                <!-- <button type="button" class="btn btn-primary btn-lg btn-block btn-pink" data-toggle="modal" data-target="#myModal"> Submit </button> -->
                <div>
                    <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Update</button>
                </div>
            </form>

        </div>
    </div>
</div>
{%endblock%}