barang/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'barang'
urlpatterns = [
    path('addbarang', addBarang, name='addBarang'),
    path('updatebarang/<str:id_barang>', updateBarang, name="updateBarang"),
    path('daftarbarang/<str:page>', listBarang, name='listBarang'),
    path('detailbarang/<str:id_barang>', detailBarang, name='detailBarang'),
    path('deletebarang/<str:id_barang>', deleteBarang, name="deletebarang"),
    path('daftarbarang/<str:kategori>/<str:page>', kategoriFiltering, name="filtering"),
    path('daftarbarang/<str:order>/<str:ini>/<str:page>', listOrdered, name="sorting"),

]

chat/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'chat'
urlpatterns = [
    path('chatanggota', chatAnggota, name='chatAnggota'),
    path('chatadmin', chatAdmin, name='chatAdmin'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login
urlpatterns = [
    path('', login),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('user/', include('user.urls')),
    path('barang/', include('barang.urls')),
    path('chat/', include('chat.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
]

barang/models.py
from django.db import models

# Create your models here.

barang/forms.py
from django import forms
from user.models import Anggota, Pengguna, Item
from django.db import connection

ITEM_CHOICES=[
    ('boneka', 'Boneka'),
    ('mahkota', 'Mahkota Princess Merk X'),
    ('masak-masakan', 'Masak-masakan'),
]

def anggota_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT a.no_ktp from anggota a, pengguna p where p.no_ktp = a.no_ktp")
        sini = cursor.fetchall()
        result = [(i[0], i[0]) for i in sini]
        return result
def item_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT nama from item")
        sini = cursor.fetchall()
        result = [(i[0], i[0]) for i in sini]
        return result
idbarang_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'ID Barang',
}

warnabarang_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Warna',
}

urlfoto_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'URL Foto',
}

kondisibarang_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Kondisi',
}

lamapenggunaan_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Lama Penggunaan',
}

persenbronze_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Persen Royalty',
}

sewabronze_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',

    'placeholder': 'Harga Sewa',
}

persensilver_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Persen Royalty',
}

sewasilver_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Harga Sewa',
}

persengold_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Persen Royalty',
}

sewagold_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder': 'Harga Sewa',
}

namaitem_attrs = {
    'class': 'form-control form-border-pink',
}

pemilikpenyewa_attrs = {
    'class': 'form-control form-border-pink',
}

class BarangForm(forms.Form):
    id_barang = forms.CharField(max_length=50, widget=forms.TextInput(attrs=idbarang_attrs))
    nama_item = forms.CharField(label='Nama item', widget=forms.Select(choices=item_choices(), attrs=namaitem_attrs))
    warna_barang = forms.CharField(max_length=50, widget=forms.TextInput(attrs=warnabarang_attrs))
    url_foto = forms.CharField(max_length=50, widget=forms.TextInput(attrs=urlfoto_attrs))
    kondisi_barang = forms.CharField(max_length=50, widget=forms.TextInput(attrs=kondisibarang_attrs))
    lama_penggunaan = forms.IntegerField(widget=forms.NumberInput(attrs=lamapenggunaan_attrs))
    pemilik_penyewa = forms.CharField(widget=forms.Select(choices=anggota_choices(), attrs=pemilikpenyewa_attrs))
    persen_bronze= forms.IntegerField(widget=forms.NumberInput(attrs=persenbronze_attrs))
    sewa_bronze = forms.IntegerField(widget=forms.NumberInput(attrs=sewabronze_attrs))
    persen_silver = forms.IntegerField(widget=forms.NumberInput(attrs=persensilver_attrs))
    sewa_silver = forms.IntegerField(widget=forms.NumberInput(attrs=sewasilver_attrs))
    persen_gold = forms.IntegerField(widget=forms.NumberInput(attrs=persengold_attrs))
    sewa_gold = forms.IntegerField(widget=forms.NumberInput(attrs=sewagold_attrs))

barang/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import BarangForm
from django.urls import reverse
from django.db import connection
from user.models import *
from django.forms import formset_factory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

def addBarang(request):
    hasil = LevelKeanggotaan.objects.raw('SELECT nama_level FROM LEVEL_KEANGGOTAAN')
    jumlah = len(hasil)
    list_nama_level = [n.nama_level for n in hasil]
    if request.method == 'POST':
        resform = BarangForm(request.POST)
        if resform.is_valid():
            save_barang(resform, list_nama_level)
            return HttpResponseRedirect("/barang/daftarbarang/1")
    forms = BarangForm()
    return render (request, 'barang/tambahbarang.html', {'forms':forms})

def updateBarang(request, id_barang):
    barang = list(Barang.objects.raw('Select * from barang where id_barang = %s', [id_barang]))
    info = list(InfoBarangLevel.objects.raw('select * from info_barang_level where id_barang = %s', [id_barang]))
    barang = {'id_barang': barang[0].id_barang,
        'nama_item': barang[0].nama_item,
        'warna_barang': barang[0].warna,
        'url_foto': barang[0].url_foto,
        'kondisi_barang': barang[0].kondisi,
        'lama_penggunaan': barang[0].lama_penggunaan,
        'pemilik_penyewa': barang[0].no_ktp_penyewa}
    
    for i in info:
        if i.nama_level == 'BRONZE':
            barang['persen_bronze'] = i.porsi_royalti
            barang['sewa_bronze'] = i.harga_sewa
        if i.nama_level == 'SILVER':
            barang['persen_silver'] = i.porsi_royalti
            barang['sewa_silver'] = i.harga_sewa
        if i.nama_level == 'GOLD':
            barang['persen_gold'] = i.porsi_royalti
            barang['sewa_gold'] = i.harga_sewa
    if request.method == 'POST':
        form = BarangForm(request.POST, initial=barang)
        if form.is_valid() and form.has_changed():
            with connection.cursor() as c:
                id_barang = barang['id_barang']
                if 'id_barang' in form.changed_data:
                    create_barang(form)
                    with connection.cursor() as c:
                        c.execute("DELETE FROM barang WHERE id_barang = %s", [barang])
                else:
                    for updated_column in form.changed_data:
                        if updated_column != 'persen_bronze' or updated_column != 'sewa_bronze' or updated_column != 'persen_silver' or updated_column != 'sewa_silver' or updated_column != 'persen_gold' or updated_column != 'sewa_gold':
                            updated_data = form.cleaned_data.get(updated_column)
                            c.execute('update barang set %s = %s where id_barang = %s' % (updated_column,'%s','%s'), [updated_data, id_barang])
                        else:
                            if updated_column == 'persen_bronze':
                                c.execute("update info_barang_level set porsi_royalti = %s where nama_level = 'bronze' and id_barang = %s", [form.cleaned_data.get('porsi_royalti', form.cleaned_data.get('id_barang'))])
                            if updated_column == 'sewa_bronze':
                                c.execute("update info_barang_level set harga_sewa = %s where nama_level = 'bronze' and id_barang = %s", [form.cleaned_data.get('harga_sewa', form.cleaned_data.get('id_barang'))])
                            if updated_column == 'persen_silver':
                                c.execute("update info_barang_level set porsi_royalti = %s where nama_level = 'silver' and id_barang = %s", [form.cleaned_data.get('porsi_royalti', form.cleaned_data.get('id_barang'))])
                            if updated_column == 'sewa_silver':
                                c.execute("update info_barang_level set harga_sewa = %s where nama_level = 'silver' and id_barang = %s", [form.cleaned_data.get('harga_sewa', form.cleaned_data.get('id_barang'))])
                            if updated_column == 'persen_gold':
                                c.execute("update info_barang_level set porsi_royalti = %s where nama_level = 'gold' and id_barang = %s", [form.cleaned_data.get('porsi_royalti', form.cleaned_data.get('id_barang'))])
                            if updated_column == 'sewa_gold':
                                c.execute("update info_barang_level set harga_sewa = %s where nama_level = 'gold' and id_barang = %s", [form.cleaned_data.get('harga_sewa', form.cleaned_data.get('id_barang'))])
            return HttpResponseRedirect('/barang/daftarbarang/1')
        else:
            print(form.errors)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        form = BarangForm(barang) 
        return render(request, 'barang/updatebarang.html', {'forms': form, 'barang_id': id_barang})

def create_barang(form):
    data_barang = [form.cleaned_data.get('id_barang'), form.cleaned_data.get('nama_item'), form.cleaned_data.get('warna_barang'), 
                            form.cleaned_data.get('url_foto'), form.cleaned_data.get('kondisi_barang'), form.cleaned_data.get('lama_penggunaan'),
                            form.cleaned_data.get('pemilik_penyewa')]
    with connection.cursor() as c:
        c.execute("INSERT INTO BARANG VALUES(%s, %s, %s, %s, %s, %s, %s)", data_barang)
        bronze = [form.cleaned_data.get('id_barang'),"BRONZE",form.cleaned_data.get('sewa_bronze'), form.cleaned_data.get('persen_bronze')]
        silver = [form.cleaned_data.get('id_barang'),"SILVER",form.cleaned_data.get('sewa_silver'), form.cleaned_data.get('persen_silver')]
        gold = [form.cleaned_data.get('id_barang'),"GOLD",form.cleaned_data.get('sewa_gold'), form.cleaned_data.get('persen_gold')]
        c.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s,%s,%s,%s)", bronze)
        c.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s,%s,%s,%s)", silver)
        c.execute("INSERT INTO INFO_BARANG_LEVEL VALUES(%s,%s,%s,%s)", gold)

def listBarang(request, page):
    barang = list(Barang.objects.raw('SELECT * FROM BARANG'))
    data = [{
        'id_barang': i.id_barang,
        'nama_item': i.nama_item,
        'warna': i.warna,
        'kondisi': i.kondisi,
    } for i in barang]
    paginator = Paginator(data, 10)
    try:
        list_barang = paginator.page(page)
    except PageNotAnInteger:
        list_barang = paginator.page(1)
    except EmptyPage:
        list_barang = paginator.page(paginator.num_pages)
    return render(request, 'barang/daftarbarang.html', {'barang': list_barang})

def detailBarang(request, id_barang):
    barang = list(Barang.objects.raw('Select * from barang where id_barang = %s', [id_barang]))
    info = list(InfoBarangLevel.objects.raw('select * from info_barang_level where id_barang = %s', [id_barang]))
    with connection.cursor() as cursor:
        cursor.execute('Select barang_dikirim.review, barang_dikirim.tanggal_review from barang_dikirim where id_barang = %s',[id_barang])
        review_query = cursor.fetchall()
        cursor.execute('Select * from info_barang_level where id_barang = %s',[id_barang])
        info_query = cursor.fetchall()

    barang = {'id_barang': barang[0].id_barang,
        'nama_item': barang[0].nama_item,
        'warna': barang[0].warna,
        'url_foto': barang[0].url_foto,
        'kondisi': barang[0].kondisi,
        'lama_penggunaan': barang[0].lama_penggunaan,
        'no_ktp_penyewa': barang[0].no_ktp_penyewa
	}

    review = [{'review': i[0],
        'tanggal_review': i[1]
    } for i in review_query]


    info = [{'id_barang': i[0],
        'nama_level': i[1],
        'harga_sewa': i[2],
        'porsi_royalti': i[3]
    } for i in info_query]
    response = {'barang': barang, 'review': review, 'info':info}
    return render(request, 'barang/detailbarang.html', response)

def deleteBarang(request, id_barang):
    with connection.cursor() as cursor:
        cursor.execute(
            'DELETE FROM BARANG where id_barang = %s', [id_barang]
        )
    return HttpResponseRedirect("/barang/daftarbarang/1")

def save_barang(barang, levels):
    toy = [barang.cleaned_data.get('id_barang'), barang.cleaned_data.get('nama_item'), barang.cleaned_data.get('warna_barang'),
           barang.cleaned_data.get('url_foto'), barang.cleaned_data.get('kondisi_barang'),
           barang.cleaned_data.get('lama_penggunaan'),
           barang.cleaned_data.get('pemilik_penyewa')]
    bronze = [barang.cleaned_data.get('id_barang'), 'BRONZE', barang.cleaned_data.get('sewa_bronze'), barang.cleaned_data.get('persen_bronze')]  
    silver = [barang.cleaned_data.get('id_barang'), 'SILVER', barang.cleaned_data.get('sewa_silver'), barang.cleaned_data.get('persen_silver')]
    gold = [barang.cleaned_data.get('id_barang'), 'GOLD', barang.cleaned_data.get('sewa_gold'), barang.cleaned_data.get('persen_gold')]
    info_datas = [bronze, silver, gold]
    with connection.cursor() as cursor:
        cursor.execute('INSERT INTO BARANG values (%s, %s, %s, %s, %s, %s, %s)', toy)
        for data in info_datas:
            cursor.execute('INSERT INTO INFO_BARANG_LEVEL values (%s, %s, %s, %s)', data)

def kategoriFiltering(request, kategori, page):
    barang = list(Barang.objects.raw('SELECT * FROM BARANG where warna = %s',[kategori]))
    data = [{
        'id_barang': i.id_barang,
        'nama_item': i.nama_item,
        'warna': i.warna,
        'kondisi': i.kondisi,
    } for i in barang]
    paginator = Paginator(data, 10)
    try:
        list_barang = paginator.page(page)
    except PageNotAnInteger:
        list_barang = paginator.page(1)
    except EmptyPage:
        list_barang = paginator.page(paginator.num_pages)
    return render(request, 'barang/daftarbarang.html', {'barang': list_barang})

def listOrdered(request, order, ini, page):
    order_q = order
    ini_q = ini
    query = "SELECT * FROM BARANG order by " + order + " " + ini

barang/templates/barang/daftarbarang.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/barang/css-barang.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Daftar Barang
{%endblock%}
{%block content%}
<div class="container">
  <div class="row p-5">
    <div class="col-12">
      <!-- Modal -->
      <div class="modal fade" id="haha" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title">Confirmation</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>

            </div>
            <div class="modal-body">
              <p>Barang berhasil ditandai</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-success" data-dismiss="modal">Ya</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
            </div>
          </div>

        </div>
      </div>
      <div class="col-10">

        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Confirmation</h4>
              </div>
              <div class="modal-body">
                <p>Apakah anda yakin untuk menghapus pengiriman tersebut?</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-success" data-dismiss="modal">Ya</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
              </div>
            </div>

          </div>
        </div>
        <div class="row">
          <div class="col-6">
            <select id="filter" style="position: relative; left: -10px; top: -5px; width: 240px; height:30px;">
              <option value="-1">Filter</option>
              <option value="Orange">Orange</option>
              <option value="Indigo">Indigo</option>
              <option value="Green">Green</option>
              <option value="Yellow">Yellow</option>
              <option value="Red">Red</option>
              <option value="Pink">Pink</option>
              <option value="Mauv">Mauv</option>
              <option value="Teal">Teal</option>
              <option value="Crimson">Crimson</option>
              <option value="Blue">Blue</option>
              <option value="pink">pink</option>
              <option value="Purple">Purple</option>
              <option value="Goldenrod">Goldenrod</option>
              <option value="Violet">Violet</option>
              <option value="Turquoise">Turquoise</option>
              <option value="Maroon">Maroon</option>
              <option value="Fuscia">Fuscia</option>
              <option value="Aquamarine">Aquamarine</option>
            </select>
          </div>
          <div class="col-6">
            <select id="sort" style="position: relative; left: -150px; top: -5px; width: 240px; height:30px;">
              <option value="-1">Sorting</option>
              <option value="1">Id barang A-Z</option>
              <option value="2">Id barang Z-A</option>
              <option value="3">Nama item A-Z</option>
              <option value="4">Nama item Z-A</option>
            </select>
          </div>
        </div>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Id Barang</th>
              <th scope="col">Nama Item</th>
              <th scope="col">Warna</th>
              <th scope="col">Kondisi</th>
              <th scope="col">Action</th>
            </tr>
          </thead>
          <tbody>
            {% for i in barang %}
            <tr>
              <td>{{ i.id_barang }}</td>
              <td>{{ i.nama_item }}</td>
              <td>{{ i.warna }}</td>
              <td>{{ i.kondisi }}</td>
              <td class="action1">
                <a href="/barang/updatebarang/{{i.id_barang}}"><button type="button"
                    class="btn btn-primary">Update</button></a>
                <button type="button" class="btn btn-danger" data-toggle="modal"
                  data-target="#m{{ forloop.counter }}">Delete
                </button>
              </td>

              <td class="action2">
                <a href="/barang/detailbarang/{{i.id_barang}}"><button type="button"
                    class="btn btn-danger">Detail</button></a>
              </td>

              <td class="action3">
                <input type="checkbox" data-toggle="modal" data-target="#haha">Tandai<br>
              </td>
              <div class="modal fade" id="m{{ forloop.counter }}">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h4 class="modal-title">DELETE NOTIFICATION</h4>
                      <button type="button" class="close" data-dismiss="modal">&times;
                      </button>
                    </div>
                    <div class="modal-body">
                      <p>Apakah anda yakin untuk menghapus pengiriman tersebut?</p>
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'barang:deletebarang' id_barang=i.id_barang %}" class="btn btn-success">Ya</a>
                      <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>

                    </div>
                  </div>
                </div>
              </div>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="view">
        {% if barang.has_other_pages %}
        <ul class="pagination">
          {% if barang.has_previous %}
          <li class="page-item"><a class="page-link"
              href="/barang/daftarbarang/{{ barang.previous_page_number }}">Previous</a></li>
          {%endif%}
          {% for i in barang.paginator.page_range %}
          {% if barang.number == i %}
          <li class="page-item active"><span class="page-link">{{i}}<span class="sr-only">(current)</span></span></li>
          {% else %}
          <li class="page-item"><a class="page-link" href="/barang/daftarbarang/{{ i }}">{{ i }}</a></li>
          {% endif %}
          {% endfor %}
          {% if barang.has_next %}
          <li class="page-item"><a class="page-link" href="/barang/daftarbarang/{{ barang.next_page_number }}">Next</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
  </div>
  {%endblock%}

  {%block script%}
  <script>
    if (localStorage.getItem('login')) {
      if (localStorage.getItem('role') == 'admin') {
        $('.action1').show();
        $('.action2').show();
        $('.action3').hide();
      } else {
        $('.action1').hide();
        $('.action2').show();
        $('.action3').show();
      }
    } else {
      $('.action1').hide();
      $('.action2').hide();
      $('.action3').hide();
    }
    $("#filter").change(function () {
      var option = $(this).val();
      if (option != -1) {
        window.location.href = "/barang/daftarbarang/" + option + "/1";
      } else {
        window.location.href = "/barang/daftarbarang/1";
      }
    });

    $("#sort").change(function () {
      var option = $(this).val();
      if (option == 1) {
        window.location.href = "/barang/daftarbarang/id_barang/ASC/1"
      } else if (option == 2) {
        window.location.href = "/barang/daftarbarang/id_barang/DESC/1"
      } else if (option == 3) {
        window.location.href = "/barang/daftarbarang/nama_item/ASC/1"
      } else if (option == 4) {
        window.location.href = "/barang/daftarbarang/nama_item/DESC/1"
      } else {
        window.location.href = "/item/list/1"
      }
    });
  </script>
  {%endblock%}

barang/templates/barang/detailbarang.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/barang/css-barang.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Detail Barang
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12">
            <h1 class="text-center font-weight-bold">Detail Barang</h1>
            <div class=" form-border update-item p-5">
                <h5>Id barang: {{barang.id_barang}}</h5>
                <h5>Deskripsi: {{barang.nama_item}}</h5>
                <h5>Warna: {{barang.warna}}</h5>
                <h5>Url foto: {{barang.url_foto}}</h5>
                <h5>Kondisi: {{barang.kondisi}}</h5>
                <h5>Lama penggunaan: {{barang.lama_penggunaan}}</h5>
                <h5>Pemilik/penyewa: {{barang.no_ktp_penyewa}}</h5>

                {%for i in review%}
                    <h5>Review: {{i.review}}</h5>
                {%endfor%}

                <h4 class="text-center font-weight-bold">Info Barang</h4>
                {%for i in info%}
                    {% if i.nama_level == 'BRONZE' %}
                        <p class="font-weight-bold">Bronze</p>
                        <h5>Persen Royalty: {{i.porsi_royalti}}</h5>
                        <h5>Harga Sewa: {{i.harga_sewa}} Rupiah/minggu</h5>
                    {%endif%}

                    {% if i.nama_level == 'SILVER' %}
                        <p class="font-weight-bold">Silver</p>
                        <h5>Persen Royalty: {{i.porsi_royalti}}</h5>                   
                        <h5>Harga Sewa: {{i.harga_sewa}} Rupiah/minggu</h5>
                    {%endif%}   

                    {% if i.nama_level == 'GOLD' %}
                        <p class="font-weight-bold">Gold</p>
                        <h5>Persen Royalty: {{i.porsi_royalti}}</h5>
                        <h5>Harga Sewa: {{i.harga_sewa}} Rupiah/minggu</h5>
                    {%endif%}
                {%endfor%}
                <a href="/pesanan/listpesanan/1"><button type="button" class="btn btn-primary">Pesan Barang</button></a>
            </div>
        </div>
    </div>
</div>
{%endblock%}

barang/templates/barang/tambahbarang.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/barang/css-barang.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Tambah Barang
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12 form-border">
            <form action="" method="post" class="p-5">
                <h1 class="text-center font-weight-bold">Tambah Barang</h1>
                {%csrf_token%}
                <div class="form-group">
                    {{forms.id_barang}}
                </div>
                <div class="form-group">
                    {{forms.nama_item}}
                </div>
                <div class="form-group">
                    {{forms.warna_barang}}
                </div>
                <div class="form-group">
                    {{forms.url_foto}}
                </div>
                <div class="form-group">
                    {{forms.kondisi_barang}}
                </div>
                <div class="form-group">
                    {{forms.lama_penggunaan}}
                </div>
                <div class="form-group">
                    {{forms.pemilik_penyewa}}
                </div>

                <h4 class="text-center font-weight-bold">Info Barang</h4>
                <p>Bronze</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_bronze}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_bronze}}
                    </div>
                </div>

                <p>Silver</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_silver}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_silver}}
                    </div>
                </div>

                <p>Gold</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_gold}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_gold}}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Tambah Barang</button>
            </form>
        </div>
    </div>
</div>

{%endblock%}

barang/templates/barang/updatebarang.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/barang/css-barang.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Update Barang
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12">
            <h1 class="text-center font-weight-bold">Update Barang</h1>
            <div class="col-12 form-border">
            <form action="" method="post" class="p-5">
                {%csrf_token%}
                <div class="form-group">
                    {{forms.id_barang}}
                </div>
                <div class="form-group">
                    {{forms.nama_item}}
                </div>
                <div class="form-group">
                    {{forms.warna_barang}}
                </div>
                <div class="form-group">
                    {{forms.url_foto}}
                </div>
                <div class="form-group">
                    {{forms.kondisi_barang}}
                </div>
                <div class="form-group">
                    {{forms.lama_penggunaan}}
                </div>
                <div class="form-group">
                    {{forms.pemilik_penyewa}}
                </div>

                <h4 class="text-center font-weight-bold">Info Barang</h4>
                <p>Bronze</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_bronze}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_bronze}}
                    </div>
                </div>

                <p>Silver</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_silver}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_silver}}
                    </div>
                </div>

                <p>Gold</p>
                <div class="form-row">
                    <div class="col-6 form-group">
                        {{forms.persen_gold}}
                    </div>
                    <div class="col-6 form-group">
                        {{forms.sewa_gold}}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Update Barang</button>
            </form>
        </div>
        </div>
    </div>
</div>
{%endblock%}