chat/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'chat'
urlpatterns = [
    path('chatanggota', chatAnggota, name='chatAnggota'),
    path('chatadmin', chatAdmin, name='chatAdmin'),
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login
urlpatterns = [
    path('', login),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('user/', include('user.urls')),
    path('barang/', include('barang.urls')),
    path('chat/', include('chat.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'user'
urlpatterns = [
    path('anggota/signup', anggotaRegister, name='anggotaRegister'),
    path('admin/signup', adminRegister, name="adminRegister"),
    path('logout', logout, name="logout"),
    path('me', profile, name="profile"),
    path('login', login, name="login")
]

user/forms.py
from django import forms


from django.core.exceptions import ValidationError

noktp_attrs = {
        'type': 'text',
        'class': 'form-control form-control-pink',
        'placeholder':'Nomor KTP',
    }




nama_attrs = {
        'type': 'text',
        'class': 'form-control form-control-pink',
        'placeholder':'Nama Lengkap',
}

email_attrs = {
    'type': 'text',
    'class': 'form-control form-control-pink',
    'placeholder':'Email',
}

tanggal_attrs = {
    'type': 'date',
    'class': 'form-control form-control-pink',
}

notelp_attrs = {
    'class': 'form-control form-control-pink',
    'placeholder':'No Telp',
}

alamat_attrs = {
    'type': 'text',
    'class': 'form-control form-control-pink',
    'placeholder':'Nama Alamat',
}

jalan_attrs = {
    'type': 'text',
    'class': 'form-control form-control-pink',
    'placeholder':'Nama jalan',
}

nomor_attrs = {
    'class': 'form-control form-control-pink',
    'placeholder':'Nomor',
}
kota_attrs = {
    'class': 'form-control form-control-pink',
    'placeholder':'Kota',
}
kodepos_attrs = {
    'class': 'form-control form-control-pink',
    'placeholder':'Kode Pos',
}

class AnggotaRegistrationForm(forms.Form):
    no_ktp = forms.CharField(max_length=200, widget=forms.TextInput(attrs=noktp_attrs))
    nama_lengkap = forms.CharField(max_length = 255, widget=forms.TextInput(attrs=nama_attrs))
    email = forms.EmailField(widget=forms.EmailInput(attrs=email_attrs))
    tanggal_lahir = forms.DateField(widget=forms.DateInput(attrs=tanggal_attrs), required=False)
    no_telp = forms.IntegerField( widget=forms.NumberInput(attrs=notelp_attrs))
    nama_alamat = forms.CharField(max_length= 255, widget=forms.TextInput(attrs=alamat_attrs))
    jalan = forms.CharField(max_length= 255, widget=forms.TextInput(attrs=jalan_attrs))
    nomor = forms.CharField(max_length= 255, widget=forms.TextInput(attrs=nomor_attrs))
    kota = forms.CharField(max_length= 255, widget=forms.TextInput(attrs=kota_attrs))
    kodepos = forms.CharField(max_length= 255, widget=forms.TextInput(attrs=kodepos_attrs))

    
class AdminRegistrationForm(forms.Form):
    no_ktp = forms.CharField(max_length=20, widget=forms.TextInput(attrs=noktp_attrs))
    nama_lengkap = forms.CharField(max_length = 255, widget=forms.TextInput(attrs=nama_attrs))
    email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs))
    tanggal_lahir = forms.DateField(widget=forms.DateInput(attrs=tanggal_attrs))
    no_telp = forms.CharField(max_length=20, widget=forms.TextInput(attrs=notelp_attrs))

class CustomLoginForm(forms.Form):
    no_ktp = forms.CharField(max_length=20, widget=forms.TextInput(attrs=noktp_attrs))
    email = forms.EmailField(widget=forms.TextInput(attrs=email_attrs))

user/views.py
from django.shortcuts import render
from .forms import AnggotaRegistrationForm, CustomLoginForm, AdminRegistrationForm
from django.contrib import messages
from django.urls import reverse
from django.db import connection
from django.http import JsonResponse, HttpResponseRedirect
from .models import *
# Create your views here.

def login(request):
    if (request.method == 'POST'):
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            no_ktp = form.cleaned_data.get('no_ktp')
            email = form.cleaned_data.get('email')
            user_exists = Pengguna.objects.raw('SELECT * FROM PENGGUNA WHERE no_ktp = %s and email = %s', [no_ktp, email])
            
            if list(user_exists):
                userisAnggota = Anggota.objects.raw('SELECT * FROM ANGGOTA WHERE no_ktp = %s', [no_ktp])
                if not list(userisAnggota):
                    print('masuk sini')
                    role = 'admin'
                else:
                    
                    role = 'anggota'
                data = {'no_ktp': no_ktp, 'email': email, 'role': role}
                request.session['no_ktp'] = no_ktp
                request.session['role'] = role
                print(request.session)
                return JsonResponse(data)  
            else:
                messages.error(request, 'Invalid email or KTP number')
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        forms = CustomLoginForm()
        return render(request, 'user/login.html', {'forms': forms})

def anggotaRegister(request):
    if request.method == 'POST':
        form = AnggotaRegistrationForm(request.POST)
        
        if form.is_valid():
            new_user = check_anggota(form)
            if new_user:
                print('masuk sini')
                return HttpResponseRedirect(reverse('user:login'))
            else:
                print("line 45")
                messages.error(request, "Error occured, Your Email or KTP Number is already on database")
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            print(form.errors)
            messages.error(request, "Error occured, have you checked your data?")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        forms = AnggotaRegistrationForm()
        return render(request, 'user/registration.html', {'forms':forms})

def adminRegister(request):
    if request.method == 'POST':
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            new_admin = check_admin(form)
            if new_admin:
                return HttpResponseRedirect(reverse('user:login'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
        else:
            print(form.errors)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        forms = AdminRegistrationForm()
        return render(request, 'user/adminregistration.html', {'forms': forms})

def profile(request):
    if (request.session['no_ktp']):
        no_ktp = request.session['no_ktp']
        with connection.cursor() as c:
            c.execute("select * from pengguna where no_ktp = %s", [no_ktp])
            pengguna_query = c.fetchall()
            if request.session['role'] == "anggota":
                c.execute("select * from anggota where no_ktp = %s", [no_ktp])
                anggota_query = c.fetchall()
                c.execute("select * from alamat where no_ktp_anggota = %s", [no_ktp])
                alamat_query = c.fetchall()
                alamat = [{'nama':i[1], 'jalan':i[2], 'nomor': i[3], 'kota': i[4], 'kodepos':i[5]}for i in alamat_query]
                data = {'no_ktp':pengguna_query[0][0], 'nama_lengkap': pengguna_query[0][1], 'email': pengguna_query[0][2], 'tanggal_lahir': pengguna_query[0][3], 'no_telp': pengguna_query[0][4]
                , 'poin': anggota_query[0][1], 'level': anggota_query[0][2], 'alamat':alamat}
            else:
                data =  {'no_ktp':pengguna_query[0][0], 'nama_lengkap': pengguna_query[0][1], 'email': pengguna_query[0][2], 'tanggal_lahir': pengguna_query[0][3], 'no_telp': pengguna_query[0][4]}
                print(data)
        return render(request, 'user/me.html',{'data': data})
    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('user:login'))

def check_anggota(form):
    data_anggota = [form.cleaned_data.get('no_ktp'), form.cleaned_data.get('nama_lengkap'), form.cleaned_data.get('email'), form.cleaned_data.get('tanggal_lahir'), form.cleaned_data.get('no_telp')]
    alamat_anggota = [form.cleaned_data.get('no_ktp'), form.cleaned_data.get('nama_alamat'), form.cleaned_data.get('jalan'),form.cleaned_data.get('nomor'), form.cleaned_data.get('kota'), form.cleaned_data.get('kodepos')]    
    ktp_exists = Anggota.objects.raw("SELECT * FROM ANGGOTA WHERE no_ktp = %s", [form.cleaned_data.get('no_ktp')])
    if list(ktp_exists):
        print("line 47")
        return False
    else:
        email_exists = Pengguna.objects.raw("SELECT * FROM PENGGUNA WHERE email= %s", [form.cleaned_data.get('email')])
        if not list(email_exists):
            with connection.cursor() as c:
                c.execute("INSERT INTO PENGGUNA VALUES(%s, %s, %s, %s, %s)", data_anggota)
                c.execute("INSERT INTO ANGGOTA VALUES(%s, 0, 'BRONZE')",[form.cleaned_data.get('no_ktp')])
                c.execute("INSERT INTO ALAMAT VALUES(%s,%s,%s,%s,%s,%s)",alamat_anggota)
            return True
        else:
            print("line 84")
            return False

def check_admin(form):
    data_admin = [form.cleaned_data.get('no_ktp'), form.cleaned_data.get('nama_lengkap'), form.cleaned_data.get('email'), form.cleaned_data.get('tanggal_lahir'), form.cleaned_data.get('no_telp')]
    ktp_exists = Anggota.objects.raw("SELECT * FROM ANGGOTA WHERE no_ktp = %s", [form.cleaned_data.get('no_ktp')])
    if list(ktp_exists):
        return False 
    else:
        email_exists = Pengguna.objects.raw("SELECT * FROM PENGGUNA WHERE email= %s", [form.cleaned_data.get('email')])
        if not list(email_exists):
            with connection.cursor() as c:
                c.execute("INSERT INTO PENGGUNA VALUES(%s, %s, %s, %s, %s)", data_admin)
                c.execute("INSERT INTO ADMIN VALUES(%s)",[form.cleaned_data.get('no_ktp')])
            return True
        else:
            return False   

user/templates/user/adminregistration.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link rel="stylesheet" href="{%static 'css/user/hira.css'%}">
{%endblock%}
{%block title%}
Anggota Register
{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-6 pt-5 text-center">
            <img class="img-fluid" src="{% static 'media/toys.jpg'%}">
            <h6 class="font-weight-bold text-gray">S T U F F E D  W I T H</h6>
            <h4 class="font-weight-bold"><span style="color:#FF7F50">T</span><span style="color:#6683CD">O</span><span style="color:#66CDAA">Y</span><span style="color:#B3289C">S </span>
                <span style="color:#FEB4BD">R</span><span style="color: #42E148">E</span><span style="color: #EFDA1F">N</span><span style="color: #FF005C">T</span></h4>
        
        </div>
        <div class="col-6">
            <div class="row pt-5">
                <div class="col-3"></div>
                <div class="col-9">
                    
                    <form action="{%url 'user:adminRegister'%}" method="post" class="form-pink p-3">
                        <h1 class="text-bold text-center">Daftar</h1>
                        {%csrf_token%}
                        <div class="form-group">
                            {{forms.no_ktp}}
                        </div>
                        <div class="form-group">
                            {{forms.nama_lengkap}}
                        </div>
                        <div class="form-group">
                            {{forms.email}}
                        </div>
                        <div class="form-group">
                            {{forms.tanggal_lahir}}
                        </div>
                        <div class="form-group">
                            {{forms.no_telp}}
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Sign Up</button>
                    </form>
                </div>
                
            </div>
            
        </div>
    </div>
</div>
{%endblock%}

user/templates/user/login.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link rel="stylesheet" href="{%static 'css/user/hira.css'%}">
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{%endblock%}
{%block title%}
Login
{%endblock%}
{%block content%}
<div class="no-login-only container">
    <div class="row">
        <div class="col-6 pt-5 text-center">
            <img class="img-fluid" src="{% static 'media/toys.jpg'%}">
            <h6 class="font-weight-bold text-gray">S T U F F E D  W I T H</h6>
            <h4 class="font-weight-bold"><span style="color:#FF7F50">T</span><span style="color:#6683CD">O</span><span style="color:#66CDAA">Y</span><span style="color:#B3289C">S </span>
                <span style="color:#FEB4BD">R</span><span style="color: #42E148">E</span><span style="color: #EFDA1F">N</span><span style="color: #FF005C">T</span></h4>
        </div>
        <div class="col-6">
            <div class="row pt-5">
                <div class="col-3"></div>
                <div class="col-9">
                    
                    <form method="post" class="form-pink p-3" action='{% url 'user:login'%}'>
                        <h1 class="text-bold text-center">Login</h1>
                        {%csrf_token%}
                        <div class="form-group">
                            {{forms.no_ktp}}
                        </div>
                        
                        <div class="form-group">
                            {{forms.email}}
                        </div>
                        
                        <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink" id="login">Sign In</button>
                    </form>
                </div>
                
            </div>
            
        </div>
    </div>
</div>
<script>
    $("#login").click(function() {
        event.preventDefault();
        $.ajax({
            headers: {"X-CSRFToken": $("input[name=csrfmiddlewaretoken]").val()},
            url:"/user/login",
            data: $("form").serialize(),
            method: 'POST',
            dataType: 'json',
            success: function(data){
                localStorage.setItem('login', true)
                localStorage.setItem('role', data.role)
                localStorage.setItem('no_ktp', data.no_ktp)
                var ref = data.role == "admin"? "/pesanan/listpesanan/1": "/barang/daftarbarang/1"
                swal({
                    title: "Hello " + data.role ,
                    text: 'You are signed in',
                    icon: 'success',
                    showConfirmButton: false,
                    timer: 2500
                    }).then(function() {
                        window.location = ref
                    });   
            }, error: function() {
                swal({
                    icon: 'error',
                    title: 'Oops...',
                    text: 'Have you checked your data?',
                    showConfirmButton: false,
                    timer: 2500
                  }).then(function() {
                      window.location = "/"
                  });
            }
        })
    });
if (localStorage.getItem('login')) {
    $(".no-login-only").hide();
}
</script>
{%endblock%}

user/templates/user/me.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link rel="stylesheet" href="{%static 'css/user/hira.css'%}">
{%endblock%}
{%block title%}
My Profile
{%endblock%}
{%block content%}
<div class="container">
    <!-- no_ktp, nama_lengkap, email, tanggal_lahir, no_telp, poin, level -->
        <div class="row">
            <div class="col-2">
                <img class="img-fluid my-3"src="https://fakeimg.pl/225/">
            </div>
            <div class="col-8 mt-3">
                <h5>Hello,</h5>
                <h1 class="font-weight-bold" id="profile-name">{{data.nama_lengkap}}</h1>
                {% if request.session.role == 'anggota' %}
                <h6 class="text-muted">My points</h6>
                <h3 class="p-0">{{data.poin}}<i class="fas fa-medal {{data.level}}"></i> </h3>
                {%else%}
                <h6 class="text-muted">My Role</h6>
                <h3 class="p-0">ADMIN</h3>
                {%endif%}
                <div class="row">
                    <div class="col-12 p-05 border-pink"></div>
                </div>
                <div class="row my-3">
                    <div class="col-12">
                        <h3 class="font-weight-bold">PROFILE</h3>
                        <p>Nomor KTP: {{data.no_ktp}}</p>
                        <p>Email: {{data.email}}</p>
                        <p>Tanggal Lahir: {{data.tanggal_lahir}}</p>
                        <p>Nomor Telpon: {{data.no_telp}}</p>
                        
                        {% if request.session.role == 'anggota' %}
                        <p class="font-weight-bold">Alamat</p>
                        {%for i in data.alamat%}
                        <p><span class="font-weight-bold">{{forloop.counter}}. {{i.nama}}: </span>{{i.jalan}} {{i.nomor}} {{i.kota}} {{i.kodepos}}</p>
                        {%endfor%}
                        {%endif%}
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock%}

user/templates/user/registration.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link rel="stylesheet" href="{%static 'css/user/hira.css'%}">
{%endblock%}
{%block title%}
Anggota Register
{%endblock%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-6 pt-5 text-center">
            <img class="img-fluid" src="{% static 'media/toys.jpg'%}">
            <h6 class="font-weight-bold text-gray">S T U F F E D  W I T H</h6>
            <h4 class="font-weight-bold"><span style="color:#FF7F50">T</span><span style="color:#6683CD">O</span><span style="color:#66CDAA">Y</span><span style="color:#B3289C">S </span>
                <span style="color:#FEB4BD">R</span><span style="color: #42E148">E</span><span style="color: #EFDA1F">N</span><span style="color: #FF005C">T</span></h4>
        
        </div>
        <div class="col-6">
            <div class="row pt-5">
                <div class="col-3"></div>
                <div class="col-9">
                    
                    <form action="{%url 'user:anggotaRegister'%}" method="POST" class="form-pink p-3">
                        <h1 class="text-bold text-center">Daftar</h1>
                        {% csrf_token %}
                        <div class="form-group">
                            {{forms.no_ktp}}
                        </div>
                        <div class="form-group">
                            {{forms.nama_lengkap}}
                        </div>
                        <div class="form-group">
                            {{forms.email}}
                        </div>
                        <div class="form-group">
                            {{forms.tanggal_lahir}}
                        </div>
                        <div class="form-group">
                            {{forms.no_telp}}
                        </div>
                        
                        <div class="form-row">
                            <div class="col-3 form-group">
                                {{forms.nama_alamat}}
                            </div>
                            <div class="col-7 form-group">
                                {{forms.jalan}}
                            </div>
                            <div class="col-2 form-group">
                                {{forms.nomor}}
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-4 form-group">
                                {{forms.kota}}
                            </div>
                            <div class="col-5 form-group">
                                {{forms.kodepos}}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Sign Up</button>
                    </form>
                </div>
                
            </div>
            
        </div>
    </div>
</div>
{%endblock%}