chat/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'chat'
urlpatterns = [
    path('chatanggota', chatAnggota, name='chatAnggota'),
    path('chatadmin', chatAdmin, name='chatAdmin'),
]

pesanan/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'pesanan'
urlpatterns = [
    path('addpesanan', addPesanan, name='addPesanan'),
    path('updatepesanan/<str:id_pemesanan>', updatePesanan, name='updatePesanan'),
    path('listpesanan/<str:page>', listPesanan, name='listPesanan'),
    path('listpesanan/<str:kategori>/<str:page>', statusFiltering, name="filtering"),
    path('deletepesanan/<str:nama>', deletePesanan, name='delete')
]

toysrent/urls.py
from django.contrib import admin
from django.urls import path, include
from user.views import login
urlpatterns = [
    path('', login),
    path('admin/', admin.site.urls),
    path('item/', include('item.urls')),
    path('user/', include('user.urls')),
    path('barang/', include('barang.urls')),
    path('chat/', include('chat.urls')),
    path('pengiriman/', include('pengiriman.urls')),
    path('review/', include('review.urls')),
    path('pesanan/', include('pesanan.urls')),
    path('level/', include('level.urls')),
]

pesanan/models.py
from django.db import models

# Create your models here.

pesanan/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.db import connection

lamasewa_attrs = {
    'type': 'text',
    'class': 'form-control form-border-pink',
    'placeholder':'Lama Sewa (hari)',
}

def anggota_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT a.no_ktp from anggota a, pengguna p where p.no_ktp = a.no_ktp")
        sini = cursor.fetchall()
        result = [(i[0], i[0]) for i in sini]
        return result

def item_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT nama_item from barang")
        sini = cursor.fetchall()
        result = [(i[0], i[0]) for i in sini]
        return result

def status_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT nama from status")
        sini = cursor.fetchall()
        result = [(i[0], i[0]) for i in sini]
        return result

pemilikpenyewa_attrs = {
    'class': 'form-control form-border-pink',
}


class PesananForm(forms.Form):
    barang = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=item_choices())
    lamasewa = forms.CharField(max_length=255, widget=forms.TextInput(attrs=lamasewa_attrs))
    anggota = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=anggota_choices())

class PesananFormAnggota(forms.Form):
    barang = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=item_choices())
    lamasewa = forms.CharField(max_length=255, widget=forms.TextInput(attrs=lamasewa_attrs))

class UpdateAdmin(forms.Form):
    barang = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=item_choices())
    lamasewa = forms.CharField(max_length=255, widget=forms.TextInput(attrs=lamasewa_attrs))
    status = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=status_choices())

class UpdateAnggota(forms.Form):
    barang = forms.MultipleChoiceField(widget=forms.SelectMultiple(attrs=pemilikpenyewa_attrs), choices=item_choices())
    lamasewa = forms.CharField(max_length=255, widget=forms.TextInput(attrs=lamasewa_attrs))

pesanan/views.py
from time import gmtime, strftime
import datetime

from django.shortcuts import render
from .forms import PesananForm, PesananFormAnggota, UpdateAdmin, UpdateAnggota
from user.models import *
from django.db import connection
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
import random
import string
# Create your views here.

def generate_harga():
    tail = random.randint(10000,999999)
    return tail

def generate_id_pemesanan():
    tail = str(random.randint(1000000000,9999999999))
    return tail

def generate_no_urut():
    tail = str(random.randint(120,999))
    return tail

def addPesanan(request):
    if request.method == 'POST':
        print("masuk post")
        no_ktp_anggota = request.session['no_ktp']
        if request.session['role'] == 'admin':
            form = PesananForm(request.POST)
            if form.is_valid():
                no_ktp_anggota = form.cleaned_data.get('anggota')
                print(no_ktp_anggota)
        else:
            form = PesananFormAnggota(request.POST)
        if form.is_valid():
            print("form valid")
            with connection.cursor() as cursor:
                id_pemesanan = generate_id_pemesanan()
                id_pemesanan_exists = list(Pemesanan.objects.raw("select * from pemesanan where id_pemesanan = %s", [id_pemesanan]))
                while id_pemesanan_exists:
                    id_pemesanan = generate_id_pemesanan()
                    id_pemesanan_exists = list(Pemesanan.objects.raw("select * from pemesanan where id_pemesanan = %s", [id_pemesanan])) 
                print(id_pemesanan)
                no_urut = generate_no_urut()
                print(no_urut)
                datetime_pemesanan = strftime('%Y-%m-%d', gmtime())
                print(datetime_pemesanan)
                kuantitas_barang = len(form.cleaned_data.get('barang'))
                harga = generate_harga()
                barang = form.cleaned_data.get('barang')
                print(barang)
                id_barang = list(Barang.objects.raw("select * from barang where nama_item = %s limit 1", barang))
                print(id_barang)
                data = [{
                    'id_barang': i.id_barang,
                } for i in id_barang]
                akhirnyadapetid = (data[0]['id_barang'])
                lama_sewa = form.cleaned_data.get('lamasewa')
                status = 'SEDANG DIKONFIRMASI'
                if request.session['role'] == 'admin':
                    no_ktp_anggota = form.cleaned_data.get('anggota')
                    no_ktp_anggota = no_ktp_anggota[0]
                else:
                    no_ktp_anggota = request.session['no_ktp']
                data_pemesanan = [id_pemesanan, datetime_pemesanan, kuantitas_barang, harga, harga, no_ktp_anggota, status]
                data_barang_pesanan = [id_pemesanan, no_urut, akhirnyadapetid, datetime_pemesanan, lama_sewa, datetime_pemesanan, status]
                cursor.execute(
                    'INSERT INTO pemesanan VALUES(%s, %s, %s, %s, %s, %s, %s)', data_pemesanan
                )
                print("masuk pemesanan")
                cursor.execute(
                    'INSERT INTO barang_pesanan VALUES(%s, %s, %s, %s, %s, %s, %s)', data_barang_pesanan
                )
                print("masuk barang pesanan")
                return HttpResponseRedirect('/pesanan/listpesanan/1')
    
    if request.session['role'] == 'admin':
        form = PesananForm()
    else:
        form = PesananFormAnggota()
    return render(request, 'pesanan/addpesanan.html', {'forms': form, 'harga': generate_harga()})

def updatePesanan(request, id_pemesanan):
    with connection.cursor() as cursor:
        cursor.execute('SELECT b.nama_item, bp.status, bp.no_urut, bp.lama_sewa FROM BARANG_PESANAN bp , BARANG b WHERE b.id_barang = bp.id_barang AND id_pemesanan=%s', [id_pemesanan])
        pesanan = cursor.fetchall()
        print(pesanan)
        cursor.execute('SELECT bp.no_urut FROM BARANG_PESANAN bp, BARANG b WHERE b.id_barang = bp.id_barang AND id_pemesanan=%s', [id_pemesanan])
        nourut = cursor.fetchall()
        print(nourut)
    if request.session['role'] == 'admin':
        pesanan = {'barang': pesanan[0][0], 'status': pesanan[0][1], 'lamasewa': pesanan[0][3]}
    else:
        pesanan = {'barang': pesanan[0][0], 'lamasewa': pesanan[0][3]}
    print(pesanan)
    print(pesanan['barang'])
    nourutfinal = nourut[0][0]
    if request.method == 'POST':
        if request.session['role'] == 'admin':
            form = UpdateAdmin(request.POST, initial=pesanan)
        else:
            form = UpdateAnggota(request.POST, initial=pesanan)
        if form.is_valid() and form.has_changed():
            with connection.cursor() as c:
                barangbaru = form.cleaned_data.get('barang')[0]
                id_barang = list(Barang.objects.raw("select * from barang where nama_item = %s limit 1", [barangbaru]))
                print(id_barang)
                data = [{
                    'id_barang': i.id_barang,
                } for i in id_barang]
                akhirnyadapetid = (data[0]['id_barang'])
                if request.session['role'] == 'admin':
                    status = form.cleaned_data.get('status')[0]
                    print(status)
                    c.execute("UPDATE barang_pesanan SET id_barang=%s, lama_sewa=%s, status=%s WHERE no_urut=%s and id_pemesanan=%s", [akhirnyadapetid, form.cleaned_data.get('lamasewa'), status, nourutfinal, id_pemesanan])
                    c.execute("UPDATE pemesanan SET status=%s WHERE id_pemesanan=%s", [status, id_pemesanan])
                else:
                    c.execute("UPDATE barang_pesanan SET id_barang=%s, lama_sewa=%s WHERE no_urut=%s and id_pemesanan=%s", [akhirnyadapetid, form.cleaned_data.get('lamasewa'), nourutfinal, id_pemesanan])
            return HttpResponseRedirect('/pesanan/listpesanan/1')
        else:
            print("dalem else luar")
            print(form.errors)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        if request.session['role'] == 'admin':
            form = UpdateAdmin(pesanan) 
        else:
            form = UpdateAnggota(pesanan)
        return render(request, 'pesanan/updatepesanan.html', {'forms': form})
    # return render(request, 'pesanan/updatepesanan.html')

def deletePesanan(request, nama):
    with connection.cursor() as c:
        c.execute("DELETE FROM barang_pesanan WHERE no_urut = %s", [nama])
    return HttpResponseRedirect('/pesanan/listpesanan/1')

def listPesanan(request, page):
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT p.id_pemesanan, b.nama_item, p.harga_sewa, p.status, bp.no_urut FROM PEMESANAN p, BARANG_PESANAN bp , BARANG b WHERE bp.id_pemesanan = p.id_pemesanan AND b.id_barang = bp.id_barang'
        )
        pesanan = cursor.fetchall()
    # print(pesanan)
    data = [{'id_pemesanan':i[0],
            'nama_item' : i[1],
            'harga_sewa': i[2],
            'status': i[3],
            'no_urut':i[4]} for i in pesanan]
    # print(data)
    paginator = Paginator(data, 10)
    try:
        dataa = paginator.page(page)
    except PageNotAnInteger:
        dataa = paginator.page(1)
    except EmptyPage:
        dataa = paginator.page(paginator.num_pages)
    return render(request, 'pesanan/daftarpesanan.html', {'pesanan':dataa})
    
def statusFiltering(request, kategori, page):
    with connection.cursor() as cursor:
        cursor.execute(
            'SELECT p.id_pemesanan, b.nama_item, p.harga_sewa, p.status, bp.no_urut FROM PEMESANAN p, BARANG_PESANAN bp , BARANG b WHERE bp.id_pemesanan = p.id_pemesanan AND b.id_barang = bp.id_barang AND p.status=%s',[kategori]
        )
        pesanan = cursor.fetchall()
    print(pesanan)
    data = [{'id_pemesanan':i[0],
            'nama_item' : i[1],
            'harga_sewa': i[2],
            'status': i[3],
            'no_urut':i[4]} for i in pesanan]
    paginator = Paginator(data, 10)
    try:
        dataa = paginator.page(page)
    except PageNotAnInteger:
        dataa = paginator.page(1)
    except EmptyPage:
        dataa = paginator.page(paginator.num_pages)
    return render(request, 'pesanan/daftarpesanan.html', {'pesanan':dataa})

pesanan/templates/pesanan/addpesanan.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/item/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Add Pesanan
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12 form-border">
            <form action="" method="post" class="p-5">
                <h1 class="text-center font-weight-bold">Tambah Pesanan</h1>
                {%csrf_token%}
                {% if request.session.role == 'admin' %}
                <div class="form-group">
                    {{forms.anggota}}
                </div>
                <div class="form-group">
                    {{forms.barang}}
                </div>
                <div class="form-group">
                    {{forms.lamasewa}}
                </div>
                {% else %}
                <div class="form-group">
                    {{forms.barang}}
                </div>
                <div class="form-group">
                    {{forms.lamasewa}}
                </div>
                {% endif %}
                <button type="button" class="btn btn-primary btn-lg btn-block btn-pink" data-toggle="modal"
                    data-target="#m{{ forloop.counter }}">Tambah Pesanan</button>


                <div class="modal fade" id="m{{ forloop.counter }}">
                    <div class="modal-dialog modal-dialog-centered">
                        <!-- Modal content-->
                        <div class="modal-content">
                            <div class="modal-header">
                                <h4 class="modal-title">Confirmation</h4>
                                <button type="button" class="close" data-dismiss="modal">&times;
                                </button>
                            </div>
                            <div class="modal-body">
                                <p>Apakah anda yakin untuk melakukan pesanan?</p>
                                <p>Total harga: Rp.{{harga}}</p>
                            </div>
                            <div class="modal-footer">
                                <a href="{% url 'pesanan:addPesanan' %}"><button type="submit"
                                        class="btn btn-success">Ya</button></a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>

                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{%endblock%}

pesanan/templates/pesanan/daftarpesanan.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/item/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
List of Items
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-9">

            <!-- Modal -->
            <div class="modal fade" id="myModal" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <h4 class="modal-title">Confirmation</h4>
                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                        </div>
                        <div class="modal-body">
                            <p>Apakah anda yakin untuk menghapus pesanan tersebut?</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-success" data-dismiss="modal">Ya</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Tidak</button>
                        </div>
                    </div>

                </div>
            </div>
            <select id="filter" style="position: relative; left: 100px; top: -5px; width: 240px; height:30px;">
                <option value="-1">Filter</option>
                <option value="SEDANG DIKONFIRMASI">SEDANG DIKONFIRMASI</option>
                <option value="SEDANG DISIAPKAN">SEDANG DISIAPKAN</option>
                <option value="SEDANG DIKIRIM">SEDANG DIKIRIM</option>
                <option value="DALAM MASA SEWA">DALAM MASA SEWA</option>
                <option value="SUDAH DIKEMBALIKAN">SUDAH DIKEMBALIKAN</option>
                <option value="BATAL">BATAL</option>
            </select>

            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Id pesanan</th>
                        <th scope="col">Daftar Barang</th>
                        <th scope="col">Harga</th>
                        <th scope="col">Status</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <!-- <th scope="row">1</th>
                        <td>
                            <ul>
                                <li>Mainan a</li>
                                <li>Mainan b</li>
                                <li>Mainan c</li>
                            </ul>
                        </td>
                        <td>Rp. 50000</td>
                        <td>Menunggu dikirim</td>
                        <td class="action1">
                            <a href="/level/updatepesanan"><button type="button"
                                    class="btn btn-primary">Update</button></a>
                        </td>
                        <td class="action2">
                            <a href="/level/updatepesanan"><button type="button"
                                    class="btn btn-primary">Update</button></a>
                            <button type="button" class="btn btn-danger" data-toggle="modal"
                                data-target="#myModal">Delete</button>
                        </td> -->
                        {% for i in pesanan %}
                        <td>{{ i.id_pemesanan }}</td>
                        <td>{{ i.nama_item }}</td>
                        <td>{{ i.harga_sewa }}</td>
                        <td>{{ i.status }}</td>
                        <td>
                            <a class="action1">
                                {% if i.status == "SEDANG DIKONFIRMASI" or i.status == "SEDANG DISIAPKAN" %}
                                <a href="/pesanan/updatepesanan/{{i.id_pemesanan}}"><button type="button"
                                        class="btn btn-primary">Update</button></a>
                                {% else %}
                                <button type="button" class="btn btn-default">Update</button>
                                {% endif %}
                            </a>
                            <a class="action2">
                                {% if i.status == "SEDANG DIKONFIRMASI" or i.status == "SEDANG DISIAPKAN" %}
                                <button type="button" class="btn btn-danger" data-toggle="modal"
                                    data-target="#m{{ forloop.counter }}">Delete
                                </button>
                                {% else %}
                                <button type="button" class="btn btn-default">Delete</button>
                                {% endif %}

                                <div class="modal fade" id="m{{ forloop.counter }}">
                                    <div class="modal-dialog modal-dialog-centered">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">DELETE NOTIFICATION</h4>
                                                <button type="button" class="close" data-dismiss="modal">&times;
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <p>Apakah anda yakin untuk menghapus pesanan tersebut?</p>
                                            </div>
                                            <div class="modal-footer">
                                                {% if i.status == "SEDANG DIKONFIRMASI" or i.status == "SEDANG DISIAPKAN" %}
                                                <a href="{% url 'pesanan:delete' nama=i.no_urut %}"
                                                    class="btn btn-success">Ya</a>
                                                {% endif %}
                                                <button type="button" class="btn btn-default"
                                                    data-dismiss="modal">Tidak</button>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    {%if pesanan.has_other_pages%}
    <div class="row">
        <div class="view">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    {%if pesanan.has_previous %}
                    <li class="page-item"><a class="page-link"
                            href="/pesanan/listpesanan/{{pesanan.previous_page_number}}">Previous</a></li>

                    {% endif %}
                    {% for i in pesanan.paginator.page_range%}
                    <li class="page-item"><a class="page-link" href="/pesanan/listpesanan/{{i}}"
                            style="color : black">{{i}}</a>
                    </li>
                    {% endfor %}
                    {% if pesanan.has_next %}
                    <li class="page-item"><a class="page-link" href="/pesanan/listpesanan/{{pesanan.next_page_number}}"
                            style="color : black">Next</a></li>

                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

    {%endif%}
</div>

{%endblock%}

{%block script%}
<script>
    if (localStorage.getItem('login')) {
        if (localStorage.getItem('role') == 'admin') {
            $('.action2').hide();
            $('.action1').show();
        } else {
            $('.action2').show();
            $('.action1').show();
        }

    } else {
        $('.action1').hide();
        $('.action2').hide();
    }

    $("#filter").change(function () {
        var option = $(this).val();
        if (option != -1) {
            window.location.href = "/pesanan/listpesanan/" + option + "/1";
        } else {
            window.location.href = "/pesanan/listpesanan/1";
        }
    });
</script>
{%endblock%}

pesanan/templates/pesanan/updatepesanan.html
{%extends "base.html"%}
{%load static%}
{%block head%}
<link href="{%static 'css/item/hira.css'%}" media="screen" rel="stylesheet" type="text/css">
{%endblock%}
{%block title%}
Update Item
{%endblock%}
{%block content%}
<div class="container">
    <div class="row p-5">
        <div class="col-12 form-border">
            <form action="" method="post" class="p-5">
                <h1 class="text-center font-weight-bold">Update Pesanan</h1>
                {%csrf_token%}
                {% if request.session.role == 'admin' %}
                <div class="form-group">
                    {{forms.barang}}
                </div>
                <div class="form-group">
                    {{forms.lamasewa}}
                </div>
                <div class="form-group">
                    {{forms.status}}
                </div>
                {% else %}
                <div class="form-group">
                    {{forms.barang}}
                </div>
                <div class="form-group">
                    {{forms.lamasewa}}
                </div>
                {% endif %}
                <button type="submit" class="btn btn-primary btn-lg btn-block btn-pink">Update Pesanan</button>
            </form>

        </div>
    </div>
</div>
{%endblock%}